### ISSUE TITLE
Add form for submitting NME plan

### ISSUE THREAD

**Issue by jimgaffneyTT** [ThetaTau/CMT#614] opened 2021-10-13 16:11 UTC
Can we add a form for Spring 2022 for chapters to submit their new member education plans, which would go directly to the RD?  I'm not sure we need a workflow as the overwhelming majority of them are approved without changes, but I'm open to suggestions.

**Comment by VenturaFranklin** [comment] 2022-01-16 17:37
Duplicate of #644

**Closed by VenturaFranklin** 2022-01-16 17:37 UTC
